### ISSUE TITLE
Typo in redis.nomad job spec

### ISSUE THREAD

**Issue by mocofound** [marco-lancini/offensive-infrastructure#4]
A typo was found in the redis.nomad job spec and appears to be causing the failed service check in your screenshot below.

Swap Out:
```
        port_map {
          sampleservicedbport = 6379
        }
```
Swap In:
```
        port_map {
          sampleservicedb_port = 6379
        }
```
See the Nomad repository for [more info](https://github.com/hashicorp/nomad/issues/7532).

Screenshot from blog post:
![image](https://www.marcolancini.it/images/posts/blog_infra_part2_nomad_job_consul.png)

**Comment by marco-lancini** [comment]
Thank you @mocofound, this has now been merged!
